name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1nTURWVdCNA1H9uVGnmN6G0zSsW_57p7A8km97UQAKg1V6unp
        USER_PASS: lzy20100122
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
